### ISSUE TITLE
想学习一下您的 theme 设计

### ISSUE THREAD

**Issue by GeneralLi95** [muzi502/muzi502.github.io#1]
母子我发现你的 theme 设计非常漂亮，文章内的引用，代码块，都有特定的格式，非常好。我想问一下你是怎么实现的呢，自定义了哪些文件或是重写了 Next 主题中的哪些内容，谢谢

**Comment by muzi502** [comment]
源码在 https://github.com/muzi502/hexo

自定义样式 https://github.com/muzi502/hexo/blob/master/source/_data/styles.styl

**Comment by GeneralLi95** [comment]
好嘞 我是在推上 看见你写的那篇文章 2019 thinking 然后来的，写的非常好。非常认同

**Comment by GeneralLi95** [comment]
抄袭完毕，晚安
